# Generated by Django 4.2.1 on 2023-05-28 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('dia', models.CharField(default=None, max_length=100, null=True, verbose_name='Dia')),
                ('horario', models.CharField(default=None, max_length=100, null=True, verbose_name='Horario')),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.clase')),
            ],
        ),
    ]
