# Generated by Django 3.2.18 on 2023-06-21 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='link',
            field=models.CharField(default='falta link', max_length=200, verbose_name='Enlace de Maps'),
            preserve_default=False,
        ),
    ]
