# Generated by Django 3.2.18 on 2023-06-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_sucursal_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='iframe',
            field=models.CharField(default='falta iframe', max_length=200, verbose_name='Script para iframe'),
            preserve_default=False,
        ),
    ]
