# Generated by Django 3.2.18 on 2023-06-04 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_alumno_profesor_sucursal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('dia', models.CharField(default=None, max_length=100, null=True, verbose_name='Dia')),
                ('horario', models.CharField(default=None, max_length=100, null=True, verbose_name='Horario')),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('estado', models.IntegerField(choices=[(1, 'Inscripto'), (2, 'Asistiendo'), (3, 'Abandonado')], default=1)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.alumno')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.grupo')),
            ],
        ),
        migrations.AddField(
            model_name='grupo',
            name='alumnos',
            field=models.ManyToManyField(through='administracion.Inscripcion', to='administracion.Alumno'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='clase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.clase'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.profesor'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.sucursal'),
        ),
    ]
