# Generated by Django 3.2.18 on 2023-06-02 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_persona_alumno_profesor_inscripcion_grupo_alumnos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('direccion', models.CharField(max_length=255, verbose_name='Direccion')),
                ('portada', models.ImageField(null=True, upload_to='imagenes/sucursal/', verbose_name='Portada')),
            ],
        ),
        migrations.AddField(
            model_name='grupo',
            name='profesor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='administracion.profesor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grupo',
            name='sucursal',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='administracion.sucursal'),
            preserve_default=False,
        ),
    ]
