# Generated by Django 3.2.18 on 2023-06-17 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0006_auto_20230617_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='numero',
            field=models.IntegerField(verbose_name='numero'),
        ),
    ]
